[[components]]
name = "babblesim_base"
dir = "components"
url = "https://github.com/BabbleSim/base"
rev = "0cc70e78a88c1de9d8ec045a703b38134861e7e7"
hash = "sha256-EFaF2Yv+oIk9KbiN0K+WV/3YqTab5Mvta2yQTgpu6jQ="

[[components]]
name = "babblesim_ext_2G4_libPhyComv1"
dir = "components/ext_2G4_libPhyComv1"
url = "https://github.com/BabbleSim/ext_2G4_libPhyComv1"
rev = "15ae0f87fa049e04cbec48a866f3bc37d903f950"
hash = "sha256-AJLqerKa9N3RE5/m5Fw3KOL3C4kROmKSiCE4RsVcCdI="

[[components]]
name = "babblesim_ext_2G4_phy_v1"
dir = "components/ext_2G4_phy_v1"
url = "https://github.com/BabbleSim/ext_2G4_phy_v1"
rev = "62e797b2c518e5bb6123a198382ed2b64b8c068e"
hash = "sha256-BMXnUbTJ1qQsrNXaDE1netxxrFZWYxhCKygI3PZ0mB8="

[[components]]
name = "babblesim_ext_2G4_channel_NtNcable"
dir = "components/ext_2G4_channel_NtNcable"
url = "https://github.com/BabbleSim/ext_2G4_channel_NtNcable"
rev = "20a38c997f507b0aa53817aab3d73a462fff7af1"
hash = "sha256-bh65lHKQ68vBT55Y/TOSC7csNDZ6+1ew+K7eR9Blrxk="

[[components]]
name = "babblesim_ext_2G4_channel_multiatt"
dir = "components/ext_2G4_channel_multiatt"
url = "https://github.com/BabbleSim/ext_2G4_channel_multiatt"
rev = "bde72a57384dde7a4310bcf3843469401be93074"
hash = "sha256-JLt2QPyPab3uGmEfCZEdI6jRye+Kdvu5Mi3fRINryFs="

[[components]]
name = "babblesim_ext_2G4_modem_magic"
dir = "components/ext_2G4_modem_magic"
url = "https://github.com/BabbleSim/ext_2G4_modem_magic"
rev = "edfcda2d3937a74be0a59d6cd47e0f50183453da"
hash = "sha256-q/GbN+5JNx3a1h1xttnRU8P3xxcB0wB4F6otnQD1F8I="

[[components]]
name = "babblesim_ext_2G4_modem_BLE_simple"
dir = "components/ext_2G4_modem_BLE_simple"
url = "https://github.com/BabbleSim/ext_2G4_modem_BLE_simple"
rev = "4d2379de510684cd4b1c3bbbb09bce7b5a20bc1f"
hash = "sha256-nWokWTpIJnc5wpl4lTizKlGtolk5tJBAeRlIm9m3nd8="

[[components]]
name = "babblesim_ext_2G4_device_burst_interferer"
dir = "components/ext_2G4_device_burst_interferer"
url = "https://github.com/BabbleSim/ext_2G4_device_burst_interferer"
rev = "5b5339351d6e6a2368c686c734dc8b2fc65698fc"
hash = "sha256-JikW/YdhTxhLAFQYq2i9Sx4kJjHrTW3Altr6ajtftZw="

[[components]]
name = "babblesim_ext_2G4_device_WLAN_actmod"
dir = "components/ext_2G4_device_WLAN_actmod"
url = "https://github.com/BabbleSim/ext_2G4_device_WLAN_actmod"
rev = "9cb6d8e72695f6b785e57443f0629a18069d6ce4"
hash = "sha256-5TRYGe0TXcbrxvHFS0p0u6nlrfLcV+FAwiFY0doGqzQ="

[[components]]
name = "babblesim_ext_2G4_device_playback"
dir = "components/ext_2G4_device_playback"
url = "https://github.com/BabbleSim/ext_2G4_device_playback"
rev = "abb48cd71ddd4e2a9022f4bf49b2712524c483e8"
hash = "sha256-BjewEmnRxyN/e6inpKVq7Yaa5hdP5OW1K0ZiyINlkIU="

[[components]]
name = "babblesim_ext_2G4_device_playbackv2"
dir = "components/ext_2G4_device_playbackv2"
url = "https://github.com/BabbleSim/ext_2G4_device_playbackv2"
rev = "0a3c28ecd59b5ee08ed4668446c243d3ffd98b46"
hash = "sha256-2AgPy7wUxvRwVT4vfaiF7VEMVSFLh78Twqzp8h9rYis="

[[components]]
name = "babblesim_ext_libCryptov1"
dir = "components/ext_libCryptov1"
url = "https://github.com/BabbleSim/ext_libCryptov1"
rev = "236309584c90be32ef12848077bd6de54e9f4deb"
hash = "sha256-fzO5SVo5t0YeDiP7SsMdxNvuhR8UotjdV/USj2oeckw="
