[manifest]
group-filter = ["-babblesim", "-bsec", "-doc-internal", "-dragoon", "-find-my", "-libmodem", "-nrf-802154"]

[[manifest.projects]]
name = "sdk-nrf"
url = "https://github.com/nrfconnect/sdk-nrf"
revision = "ba167d9f3db4abbdc9b67887ca3ea66c64f2d956"
path = "nrf"
west-commands = "scripts/west-commands.yml"

[manifest.projects.nix]
hash = "sha256-5yjXNLnWkGYEyJDhCbkOSpIUotZVnSa6RM06B8doM4k="

[[manifest.projects]]
name = "zephyr"
url = "https://github.com/nrfconnect/sdk-zephyr"
revision = "fd9204a02d52630660ce8d729945a4dd743feabf"
west-commands = "scripts/west-commands.yml"

[manifest.projects.nix]
hash = "sha256-qCSX2Zc3/SyFc0BhSGfmXqflJx55+is8PPp+SxQWXuU="

[[manifest.projects]]
name = "wfa-qt-control-app"
url = "https://github.com/nrfconnect/sdk-wi-fiquicktrack-controlappc"
revision = "63b3fa8bab483d021dd8c09a581887b039aa9e8a"
path = "modules/lib/wfa-qt-control-app"

[manifest.projects.userdata.ncs]
upstream-url = "https://github.com/Wi-FiQuickTrack/Wi-FiQuickTrack-ControlAppC"
upstream-sha = "1225729e8d84075f03bf9fc51eee85d84dfb0091"
compare-by-default = true

[manifest.projects.nix]
hash = "sha256-/LnP76r/fBOFn1Rt849c9SKsRtClOVVp0yv+3KK+tkM="

[[manifest.projects]]
name = "mcuboot"
url = "https://github.com/nrfconnect/sdk-mcuboot"
revision = "fce4dac2e6295cf98bd02a85f7c4254f6102106d"
path = "bootloader/mcuboot"

[manifest.projects.nix]
hash = "sha256-A01ZziduPNcOigrGqa54Yzann6NFPb2/bKhKKbBYXZE="

[[manifest.projects]]
name = "qcbor"
url = "https://github.com/laurencelundblade/QCBOR"
revision = "751d36583a9ce1a640900c57e13c9b6b8f3a2ba2"
path = "modules/tee/tf-m/qcbor"

[manifest.projects.nix]
hash = "sha256-heOCeSDrHCJA2T/iRnSXoRIl6WeS8KRDtEh9zK1Hkm8="

[[manifest.projects]]
name = "mbedtls"
url = "https://github.com/nrfconnect/sdk-mbedtls"
revision = "5bb86aeae32420e4f537e5cc390f7219a1bcf500"
path = "modules/crypto/mbedtls"

[manifest.projects.nix]
hash = "sha256-HCFQt0u31svP0YaYI/2JOi+k6nXMd+oBY2587QuI/AE="

[[manifest.projects]]
name = "oberon-psa-crypto"
url = "https://github.com/nrfconnect/sdk-oberon-psa-crypto"
revision = "fd1f2aa156d8beb78584dfbaf30df30bf8f6568f"
path = "modules/crypto/oberon-psa-crypto"

[manifest.projects.nix]
hash = "sha256-5lIATXL0tFElK8mi6CyNJhnU/C2kjXndegdk6HRPmiQ="

[[manifest.projects]]
name = "nrfxlib"
url = "https://github.com/nrfconnect/sdk-nrfxlib"
revision = "cfb98f4bcd4efe00df0c741e137b42f307680402"

[manifest.projects.nix]
hash = "sha256-PKhOuvRtx21VmTcFPrawpSLjaBxF5hde1Oul153GS6I="

[[manifest.projects]]
name = "trusted-firmware-m"
url = "https://github.com/nrfconnect/sdk-trusted-firmware-m"
revision = "4f72bf583e71503965aed78f819474f25ce45a81"
path = "modules/tee/tf-m/trusted-firmware-m"

[manifest.projects.nix]
hash = "sha256-Lnkyf27mSdXjvAUcKD39HXkAGud1GTIoJn+S4ucrgS0="

[[manifest.projects]]
name = "psa-arch-tests"
url = "https://github.com/nrfconnect/sdk-psa-arch-tests"
revision = "ba0487c40eb2b57676676604b4c17526790dbc94"
path = "modules/tee/tf-m/psa-arch-tests"

[manifest.projects.nix]
hash = "sha256-6Aey+nP927oVZTxyCDVYLsVfcn23PPU4ZVtAZVsPrH4="

[[manifest.projects]]
name = "matter"
url = "https://github.com/nrfconnect/sdk-connectedhomeip"
revision = "47099d700f9b4713d914cfeee62680548ecde190"
path = "modules/lib/matter"
west-commands = "scripts/west/west-commands.yml"

[[manifest.projects.submodules]]
path = "third_party/nlio/repo"
name = "nlio"

[[manifest.projects.submodules]]
path = "third_party/nlassert/repo"
name = "nlassert"

[[manifest.projects.submodules]]
path = "third_party/pigweed/repo"
name = "pigweed"

[[manifest.projects.submodules]]
path = "third_party/jsoncpp/repo"
name = "jsoncpp"

[manifest.projects.userdata.ncs]
upstream-url = "https://github.com/project-chip/connectedhomeip"
upstream-sha = "181b0cb14ff007ec912f2ba6627e05dfb066c008"
compare-by-default = false

[manifest.projects.nix]
hash = "sha256-8vld4OxHn9nBOX0btber5ml2amu9vUmROx6GOF77Wgo="

[[manifest.projects]]
name = "cjson"
url = "https://github.com/nrfconnect/sdk-cjson"
revision = "c6af068b7f05207b28d68880740e4b9ec1e4b50a"
path = "modules/lib/cjson"

[manifest.projects.userdata.ncs]
upstream-url = "https://github.com/DaveGamble/cJSON"
upstream-sha = "d2735278ed1c2e4556f53a7a782063b31331dbf7"
compare-by-default = false

[manifest.projects.nix]
hash = "sha256-2WtrP+Dam6iFE5jRPskMxss82KfG7Sf+nc7Y+IuggDc="

[[manifest.projects]]
name = "azure-sdk-for-c"
url = "https://github.com/nrfconnect/azure-sdk-for-c"
revision = "308c171cb4b5eed266649012a68406487ec81fb2"
path = "modules/lib/azure-sdk-for-c"

[manifest.projects.userdata.ncs]
upstream-url = "https://github.com/Azure/azure-sdk-for-c"
upstream-sha = "adc56bc6138a28b5490bce339a31a2581a072092"
compare-by-default = false

[manifest.projects.nix]
hash = "sha256-sBnvtWz9QH4lrb3q+xI/MqFO8LWrhVN8+VsHX0RdZSM="

[[manifest.projects]]
name = "cirrus"
url = "https://github.com/nrfconnect/sdk-mcu-drivers"
revision = "1c837bcc27de9ccc06b020b9500e1547e559a1df"
path = "modules/hal/cirrus-logic"

[manifest.projects.userdata.ncs]
upstream-url = "https://github.com/CirrusLogic/mcu-drivers"
upstream-sha = "1be6ca7253133a21a1e9fe0fbb4656e17d63a936"
compare-by-default = false

[manifest.projects.nix]
hash = "sha256-L8jHNR22n27dkP7XqJ/pQ0U1QcaC2gt02W+P9P3L/DA="

[[manifest.projects]]
name = "openthread"
url = "https://github.com/nrfconnect/sdk-openthread"
revision = "0e26667136c2c49d42c96b8104ec2e90e8d55e4d"
path = "modules/lib/openthread"

[manifest.projects.userdata.ncs]
upstream-url = "https://github.com/openthread/openthread"
upstream-sha = "c6eaeda5a1c1c5dbb24dce7e027340cb8893a77b"
compare-by-default = false

[manifest.projects.nix]
hash = "sha256-MzsrLeklp1simIwJh2Y0b7dKNlMkal6SlNHXFvpqyfE="

[[manifest.projects]]
name = "cmock"
url = "https://github.com/ThrowTheSwitch/cmock"
revision = "f65066f15d8248e6dcb778efb8739904a4512087"
path = "test/cmock"
submodules = true

[manifest.projects.nix]
hash = "sha256-0JbIT3db/NlBtkf6xCIVtYsWiC0j9RCYAKbBhrroyoA="

[[manifest.projects]]
name = "memfault-firmware-sdk"
url = "https://github.com/memfault/memfault-firmware-sdk"
revision = "5ee5e5af88630da814fccdd126421f32280d6538"
path = "modules/lib/memfault-firmware-sdk"

[manifest.projects.nix]
hash = "sha256-w0d3R4YzcdrBKfP/FVI7wEwj1vsQEWdlaJQvzlXqxG4="

[[manifest.projects]]
name = "bsim"
url = "https://github.com/BabbleSim/bsim_west"
revision = "a88d3353451387ca490a6a7f7c478a90c4ee05b7"
path = "tools/bsim"

[manifest.projects.nix]
hash = "sha256-fukVH/2GJtWw3YWrTWSzMEW80jqdhWq8xhlt/0xhxrI="

[[manifest.projects]]
name = "coremark"
url = "https://github.com/eembc/coremark"
revision = "d5fad6bd094899101a4e5fd53af7298160ced6ab"
path = "modules/benchmark/coremark"
groups = ["benchmark"]

[manifest.projects.nix]
hash = "sha256-KBzkjRV24chI7iLLCIFNXVTEgFv9/+DvzWH0aeq6QAU="

[[manifest.projects]]
name = "hostap"
url = "https://github.com/nrfconnect/sdk-hostap"
revision = "957e9578648b7da0e35f20dbf9a0c35fce9dc4af"
path = "modules/lib/hostap"

[manifest.projects.nix]
hash = "sha256-42h8GaHSCZ6Qhb65rTy73ZGtdTyEtYl50ZwHRA6rrfc="

[[manifest.projects]]
name = "canopennode"
url = "https://github.com/zephyrproject-rtos/canopennode"
revision = "dec12fa3f0d790cafa8414a4c2930ea71ab72ffd"
path = "modules/lib/canopennode"
groups = ["optional"]

[manifest.projects.nix]
hash = "sha256-BbmEjeMzKznRDx329PIkmPMCGI+du6wiOj+3X7Ap1HQ="

[[manifest.projects]]
name = "chre"
url = "https://github.com/zephyrproject-rtos/chre"
revision = "3b32c76efee705af146124fb4190f71be5a4e36e"
path = "modules/lib/chre"
groups = ["optional"]

[manifest.projects.nix]
hash = "sha256-7SdP9zSKZ+6s+nkIcIbjZSnacq2/t06DiR2gcaL07T4="

[[manifest.projects]]
name = "cmsis"
url = "https://github.com/zephyrproject-rtos/cmsis"
revision = "512cc7e895e8491696b61f7ba8066b4a182569b8"
path = "modules/hal/cmsis"
groups = ["hal"]

[manifest.projects.nix]
hash = "sha256-IR4Za8TuYY7nkqK57xUJ2uWnCp7wB9B4/ZjhalLhCUU="

[[manifest.projects]]
name = "cmsis-dsp"
url = "https://github.com/zephyrproject-rtos/cmsis-dsp"
revision = "97512610ec92058f0119450b9e743eeb7e95b5c8"
path = "modules/lib/cmsis-dsp"

[manifest.projects.nix]
hash = "sha256-Lxmu9fPuLtaPiDRhZWLYoihKC6TEBb5j3iTouT6Vv3E="

[[manifest.projects]]
name = "cmsis-nn"
url = "https://github.com/zephyrproject-rtos/cmsis-nn"
revision = "e9328d612ea3ea7d0d210d3ac16ea8667c01abdd"
path = "modules/lib/cmsis-nn"

[manifest.projects.nix]
hash = "sha256-bD/58SYlCnBjBT6quUi3QH0dK49GgA8OqoLOKArQEik="

[[manifest.projects]]
name = "cmsis_6"
url = "https://github.com/zephyrproject-rtos/CMSIS_6"
revision = "30a859f44ef8ab4dc8f84b03ed586fd16ccf9d74"
path = "modules/hal/cmsis_6"
groups = ["hal"]

[manifest.projects.nix]
hash = "sha256-nTehISN0pu9gnOZMpGaBQ3DFmNxAqAZPGpvbKfEM35o="

[[manifest.projects]]
name = "edtt"
url = "https://github.com/zephyrproject-rtos/edtt"
revision = "c282625e694f0b53ea53e13231ea6d2f49411768"
path = "tools/edtt"
groups = ["tools"]

[manifest.projects.nix]
hash = "sha256-6RRsNcqAMIIgZnSXCppjvh8oKzeLvuPTWY7rZBABRYM="

[[manifest.projects]]
name = "fatfs"
url = "https://github.com/zephyrproject-rtos/fatfs"
revision = "f4ead3bf4a6dab3a07d7b5f5315795c073db568d"
path = "modules/fs/fatfs"
groups = ["fs"]

[manifest.projects.nix]
hash = "sha256-E7ULrWZMg7ZO7SaygLEkJ6mPJoHKdvpHgNxIUgYzics="

[[manifest.projects]]
name = "hal_nordic"
url = "https://github.com/zephyrproject-rtos/hal_nordic"
revision = "1acb428a205bad58f3dfd4e38f2d1663bb784ba1"
path = "modules/hal/nordic"
groups = ["hal"]

[manifest.projects.nix]
hash = "sha256-3Dqce3iu+sUCKZcJUSN1y1h5EcruWLCOA03zNr8wLw8="

[[manifest.projects]]
name = "hal_st"
url = "https://github.com/zephyrproject-rtos/hal_st"
revision = "6d963459acecfd2f9748ab506385a3188d8768f0"
path = "modules/hal/st"
groups = ["hal"]

[manifest.projects.nix]
hash = "sha256-JRskR6CwyROY0YIAuoIW+C5W0r/OHBAWlJFrpbhHMGE="

[[manifest.projects]]
name = "hal_tdk"
url = "https://github.com/zephyrproject-rtos/hal_tdk"
revision = "60708f2c7bf078bc9cc3a7737ef955ec572c23e2"
path = "modules/hal/tdk"
groups = ["hal"]

[manifest.projects.nix]
hash = "sha256-Ys6KGdOE00owxLRs9ou0RYFjijafw2365l63xQxa8pM="

[[manifest.projects]]
name = "hal_wurthelektronik"
url = "https://github.com/zephyrproject-rtos/hal_wurthelektronik"
revision = "7c1297ea071d03289112eb24e789c89c7095c0a2"
path = "modules/hal/wurthelektronik"
groups = ["hal"]

[manifest.projects.nix]
hash = "sha256-P0059SiUPvlf2r3I/zkHTyJxharmuD0EOZpmFjxqf3w="

[[manifest.projects]]
name = "liblc3"
url = "https://github.com/zephyrproject-rtos/liblc3"
revision = "48bbd3eacd36e99a57317a0a4867002e0b09e183"
path = "modules/lib/liblc3"

[manifest.projects.nix]
hash = "sha256-OWuj68+YztIh/dPvwqjW7ch7Ph3aiEIDvO9rMkVIrQ8="

[[manifest.projects]]
name = "libmetal"
url = "https://github.com/zephyrproject-rtos/libmetal"
revision = "66e084293b2a7ced5a73fbd247deddba8915883a"
path = "modules/hal/libmetal"
groups = ["hal"]

[manifest.projects.nix]
hash = "sha256-W1clIg/50idqyhaosO/1egQ7uxTrm3j7ghNfcQlfqo4="

[[manifest.projects]]
name = "libsbc"
url = "https://github.com/zephyrproject-rtos/libsbc"
revision = "8e1beda02acb8972e29e6edbb423f7cafe16e445"
path = "modules/lib/libsbc"

[manifest.projects.nix]
hash = "sha256-paQEQH9ZfA0yq/FjI6DIoBkNm8E/5eo+jl6yqdabaIY="

[[manifest.projects]]
name = "littlefs"
url = "https://github.com/zephyrproject-rtos/littlefs"
revision = "8f5ca347843363882619d8f96c00d8dbd88a8e79"
path = "modules/fs/littlefs"
groups = ["fs"]

[manifest.projects.nix]
hash = "sha256-MuXfpmEE3z0ZOtfjp93aAh/7xZhShmHzwHC5nyN2QQg="

[[manifest.projects]]
name = "loramac-node"
url = "https://github.com/zephyrproject-rtos/loramac-node"
revision = "fb00b383072518c918e2258b0916c996f2d4eebe"
path = "modules/lib/loramac-node"

[manifest.projects.nix]
hash = "sha256-t6CRkm5TheFvUuc+Qj3JaveWYOaHRH6Pquvlb5YlsOg="

[[manifest.projects]]
name = "lvgl"
url = "https://github.com/zephyrproject-rtos/lvgl"
revision = "94ae6c0535aa6ac4b08a75f4ae2c3a08cacb5c41"
path = "modules/lib/gui/lvgl"

[manifest.projects.nix]
hash = "sha256-YzkRpNX/oBYxb/2kG77duMmRyJFm5gCgnyPpo0NfBFU="

[[manifest.projects]]
name = "mipi-sys-t"
url = "https://github.com/zephyrproject-rtos/mipi-sys-t"
revision = "5a9d6055b62edc54566d6d0034d9daec91749b98"
path = "modules/debug/mipi-sys-t"
groups = ["debug"]

[manifest.projects.nix]
hash = "sha256-RRBCobeVbDP/o6/PALFqNLc5x78LkSx55P8sQic5YQI="

[[manifest.projects]]
name = "nanopb"
url = "https://github.com/zephyrproject-rtos/nanopb"
revision = "5499fd4c9a478f8139eeb07a82c3b4468d6067f7"
path = "modules/lib/nanopb"

[manifest.projects.nix]
hash = "sha256-QYp+jFuVZlfR5R98/7Pr7CQWvManBl+oP8eXq1OEBsQ="

[[manifest.projects]]
name = "net-tools"
url = "https://github.com/zephyrproject-rtos/net-tools"
revision = "64d7acc661ae2772282570f21beab85d02f2f35c"
path = "tools/net-tools"
groups = ["tools"]

[manifest.projects.nix]
hash = "sha256-//yqbV1b4hp7IYhgcJ5RfoEX5bvr7wU/z/Lv+frBNOM="

[[manifest.projects]]
name = "nrf_hw_models"
url = "https://github.com/zephyrproject-rtos/nrf_hw_models"
revision = "63ccab2988bf4c144b3cd324a0277e03206fa413"
path = "modules/bsim_hw_models/nrf_hw_models"

[manifest.projects.nix]
hash = "sha256-qg6vcOrizX5kkx4kDDfEK2C3ObOESYTODWQ1Gd2AH1Y="

[[manifest.projects]]
name = "nrf_wifi"
url = "https://github.com/zephyrproject-rtos/nrf_wifi"
revision = "1a4e59f4c6685877f6bff08bb1812bf9318da6d2"
path = "modules/lib/nrf_wifi"

[manifest.projects.nix]
hash = "sha256-WO7x8CuZtBcfTrt4iiQXZq73Rw2yJWE2Cxha57NSrMk="

[[manifest.projects]]
name = "open-amp"
url = "https://github.com/zephyrproject-rtos/open-amp"
revision = "5efe7974f9546582e99f5a842a816ea4b65f5227"
path = "modules/lib/open-amp"

[manifest.projects.nix]
hash = "sha256-RMY5ZqV+39FWqZU1rDosE8I2HqWPd6PvSMMVuPsdMS8="

[[manifest.projects]]
name = "percepio"
url = "https://github.com/zephyrproject-rtos/percepio"
revision = "132ed87d617578a6cb70a2443f43e117c315e0f0"
path = "modules/debug/percepio"
groups = ["debug"]

[manifest.projects.nix]
hash = "sha256-BSN06+3hoofJOJf/67JJVNOPmUlAzqpnsa24umEsV0o="

[[manifest.projects]]
name = "picolibc"
url = "https://github.com/zephyrproject-rtos/picolibc"
revision = "ca8b6ebba5226a75545e57a140443168a26ba664"
path = "modules/lib/picolibc"

[manifest.projects.nix]
hash = "sha256-8/SEuAwRLlQmI/UnMwErhuZSg0nLgNNgKJfzFt4YcnI="

[[manifest.projects]]
name = "segger"
url = "https://github.com/zephyrproject-rtos/segger"
revision = "50892fdbcf2f570e67baa72b8894a66b16946f72"
path = "modules/debug/segger"
groups = ["debug"]

[manifest.projects.nix]
hash = "sha256-EyrMOzsD8hClcAc778TsBe3dEFMtRAAeLzPxYK8NRcQ="

[[manifest.projects]]
name = "tf-m-tests"
url = "https://github.com/zephyrproject-rtos/tf-m-tests"
revision = "cde5b6ed540d3ff5a09564fded6b39b0a70ad3bf"
path = "modules/tee/tf-m/tf-m-tests"
groups = ["testing", "tee"]

[manifest.projects.nix]
hash = "sha256-shhgtNblMRP2T1DEq5CQAZfI64OxZrNKKT7P9ui8dh8="

[[manifest.projects]]
name = "uoscore-uedhoc"
url = "https://github.com/zephyrproject-rtos/uoscore-uedhoc"
revision = "ac80c3bf2b88deec86d129654fbde09761582342"
path = "modules/lib/uoscore-uedhoc"

[manifest.projects.nix]
hash = "sha256-+LDLpCvlgvY1iTAgfX2gOCW8kPuOo5fOJSCmKSGct9U="

[[manifest.projects]]
name = "zcbor"
url = "https://github.com/zephyrproject-rtos/zcbor"
revision = "9164bd18dcd88ff9d9ef98279501fc1093571017"
path = "modules/lib/zcbor"

[manifest.projects.nix]
hash = "sha256-2lgS4KXxy3BsZvGn75vqu+v5lJOil7G1aq3/iQauH9s="

[manifest.self]
path = "MockingBeacon"
