[manifest]
group-filter = ["-babblesim", "-bsec", "-doc-internal", "-dragoon", "-find-my", "-libmodem", "-nrf-802154"]

[[manifest.projects]]
name = "sdk-nrf"
url = "https://github.com/nrfconnect/sdk-nrf"
revision = "6c6e5b32496eb7203f4c52ae9b3575949eab522e"
path = "nrf"
west-commands = "scripts/west-commands.yml"

[manifest.projects.nix]
hash = "sha256-gs+CFobu5/UqSoL90jktrCdIJ/pBfT4SQMxSa5VzeJ4="

[[manifest.projects]]
name = "zephyr"
url = "https://github.com/nrfconnect/sdk-zephyr"
revision = "1612683d4010b571be79f21d86edf683aac37679"
west-commands = "scripts/west-commands.yml"

[manifest.projects.nix]
hash = "sha256-B7ROHCcbURCFNx2oxSOkziIeFSdatCQhVNAj0O0NGtg="

[[manifest.projects]]
name = "hostap"
url = "https://github.com/nrfconnect/sdk-hostap"
revision = "2b5c82cd4e833c065075bc239a7bd138d4662e34"
path = "modules/lib/hostap"

[manifest.projects.nix]
hash = "sha256-xD7/NWeYIX9ATZLOBSsCU6ksg9UDFFqlY3HGOXM1JwU="

[[manifest.projects]]
name = "wfa-qt-control-app"
url = "https://github.com/nrfconnect/sdk-wi-fiquicktrack-controlappc"
revision = "d4bc010be69aa89290c5af6767702ff46c1829e5"
path = "modules/lib/wfa-qt-control-app"

[manifest.projects.userdata.ncs]
upstream-url = "https://github.com/Wi-FiQuickTrack/Wi-FiQuickTrack-ControlAppC"
upstream-sha = "1225729e8d84075f03bf9fc51eee85d84dfb0091"
compare-by-default = true

[manifest.projects.nix]
hash = "sha256-hDBebap/ENTqyC8FHtsUhDlLOTLiknKvaXfUexGJO0s="

[[manifest.projects]]
name = "mcuboot"
url = "https://github.com/nrfconnect/sdk-mcuboot"
revision = "2b69d93e75bcdcf5a06e578a4b7ac0e81f410fec"
path = "bootloader/mcuboot"

[manifest.projects.nix]
hash = "sha256-919zKzLNEamxmzT4kpd7JZng4wL+YYQ8XL38hfCGnok="

[[manifest.projects]]
name = "qcbor"
url = "https://github.com/laurencelundblade/QCBOR"
revision = "751d36583a9ce1a640900c57e13c9b6b8f3a2ba2"
path = "modules/tee/tf-m/qcbor"

[manifest.projects.nix]
hash = "sha256-heOCeSDrHCJA2T/iRnSXoRIl6WeS8KRDtEh9zK1Hkm8="

[[manifest.projects]]
name = "mbedtls"
url = "https://github.com/nrfconnect/sdk-mbedtls"
revision = "c5115abac477249fab42e61368b8f87c3c9265e1"
path = "modules/crypto/mbedtls"

[manifest.projects.nix]
hash = "sha256-WtUOY6MH0PsrLxIwJ/kNXXn5skzpGl3pBdiWyYluRMo="

[[manifest.projects]]
name = "oberon-psa-crypto"
url = "https://github.com/nrfconnect/sdk-oberon-psa-crypto"
revision = "975ee6386efeec257e6af206706ecd27860a07cb"
path = "modules/crypto/oberon-psa-crypto"

[manifest.projects.nix]
hash = "sha256-BcDhJEK5uEaqRgLvxW7iS0OxnBq7oPDgL13qFnd0SZA="

[[manifest.projects]]
name = "nrfxlib"
url = "https://github.com/nrfconnect/sdk-nrfxlib"
revision = "3b210a24d3bc7ecfc268e0feab6436306b11e7cb"

[manifest.projects.nix]
hash = "sha256-dVkTheV89K3UN8TR3gvvzamzaXEtBkRcxwd6J0q7tUU="

[[manifest.projects]]
name = "trusted-firmware-m"
url = "https://github.com/nrfconnect/sdk-trusted-firmware-m"
revision = "44bbc980ed6bcc7583d5bf532991f804d8ef0ea6"
path = "modules/tee/tf-m/trusted-firmware-m"

[manifest.projects.nix]
hash = "sha256-W3YD+2vAocwdW7wzlD/p9mhd5EMCrnDgt1qjJ+p/yks="

[[manifest.projects]]
name = "psa-arch-tests"
url = "https://github.com/nrfconnect/sdk-psa-arch-tests"
revision = "3da9313e64806d352c519e3205e81cf959067588"
path = "modules/tee/tf-m/psa-arch-tests"

[manifest.projects.nix]
hash = "sha256-y5XR1Dk8/8lM6CMSvaEqBwxQtxrM7qX3XniezwEdkB8="

[[manifest.projects]]
name = "matter"
url = "https://github.com/nrfconnect/sdk-connectedhomeip"
revision = "b5e4e997db07a9d53b8539b9bf7018f6c638fd7b"
path = "modules/lib/matter"
west-commands = "scripts/west/west-commands.yml"

[[manifest.projects.submodules]]
path = "third_party/nlio/repo"
name = "nlio"

[[manifest.projects.submodules]]
path = "third_party/nlassert/repo"
name = "nlassert"

[[manifest.projects.submodules]]
path = "third_party/pigweed/repo"
name = "pigweed"

[[manifest.projects.submodules]]
path = "third_party/jsoncpp/repo"
name = "jsoncpp"

[manifest.projects.userdata.ncs]
upstream-url = "https://github.com/project-chip/connectedhomeip"
upstream-sha = "181b0cb14ff007ec912f2ba6627e05dfb066c008"
compare-by-default = false

[manifest.projects.nix]
hash = "sha256-AaKvg48CntkRL2tH+siRJkn6yX3+qQZxCV73mvC1vf4="

[[manifest.projects]]
name = "cjson"
url = "https://github.com/nrfconnect/sdk-cjson"
revision = "c6af068b7f05207b28d68880740e4b9ec1e4b50a"
path = "modules/lib/cjson"

[manifest.projects.userdata.ncs]
upstream-url = "https://github.com/DaveGamble/cJSON"
upstream-sha = "d2735278ed1c2e4556f53a7a782063b31331dbf7"
compare-by-default = false

[manifest.projects.nix]
hash = "sha256-2WtrP+Dam6iFE5jRPskMxss82KfG7Sf+nc7Y+IuggDc="

[[manifest.projects]]
name = "azure-sdk-for-c"
url = "https://github.com/nrfconnect/azure-sdk-for-c"
revision = "308c171cb4b5eed266649012a68406487ec81fb2"
path = "modules/lib/azure-sdk-for-c"

[manifest.projects.userdata.ncs]
upstream-url = "https://github.com/Azure/azure-sdk-for-c"
upstream-sha = "adc56bc6138a28b5490bce339a31a2581a072092"
compare-by-default = false

[manifest.projects.nix]
hash = "sha256-sBnvtWz9QH4lrb3q+xI/MqFO8LWrhVN8+VsHX0RdZSM="

[[manifest.projects]]
name = "cirrus"
url = "https://github.com/nrfconnect/sdk-mcu-drivers"
revision = "3873a08377d93a479105a75ac390d3bbcd31d690"
path = "modules/hal/cirrus-logic"

[manifest.projects.userdata.ncs]
upstream-url = "https://github.com/CirrusLogic/mcu-drivers"
upstream-sha = "1be6ca7253133a21a1e9fe0fbb4656e17d63a936"
compare-by-default = false

[manifest.projects.nix]
hash = "sha256-zNRoNsjkTHjiAebLxlzFQiFpJloo86Ee23KiaCp3DT4="

[[manifest.projects]]
name = "openthread"
url = "https://github.com/nrfconnect/sdk-openthread"
revision = "0e26667136c2c49d42c96b8104ec2e90e8d55e4d"
path = "modules/lib/openthread"

[manifest.projects.userdata.ncs]
upstream-url = "https://github.com/openthread/openthread"
upstream-sha = "c6eaeda5a1c1c5dbb24dce7e027340cb8893a77b"
compare-by-default = false

[manifest.projects.nix]
hash = "sha256-MzsrLeklp1simIwJh2Y0b7dKNlMkal6SlNHXFvpqyfE="

[[manifest.projects]]
name = "cmock"
url = "https://github.com/ThrowTheSwitch/cmock"
revision = "f65066f15d8248e6dcb778efb8739904a4512087"
path = "test/cmock"
submodules = true

[manifest.projects.nix]
hash = "sha256-0JbIT3db/NlBtkf6xCIVtYsWiC0j9RCYAKbBhrroyoA="

[[manifest.projects]]
name = "memfault-firmware-sdk"
url = "https://github.com/memfault/memfault-firmware-sdk"
revision = "36e2597083b3fee8afe629a3b3441f3d1ebe66ae"
path = "modules/lib/memfault-firmware-sdk"

[manifest.projects.nix]
hash = "sha256-gsMlzhGhwp6akvAb2aQ50coz4R/IHTYuNThw01VU3oQ="

[[manifest.projects]]
name = "bsim"
url = "https://github.com/BabbleSim/bsim_west"
revision = "a88d3353451387ca490a6a7f7c478a90c4ee05b7"
path = "tools/bsim"

[manifest.projects.nix]
hash = "sha256-fukVH/2GJtWw3YWrTWSzMEW80jqdhWq8xhlt/0xhxrI="

[[manifest.projects]]
name = "coremark"
url = "https://github.com/eembc/coremark"
revision = "d5fad6bd094899101a4e5fd53af7298160ced6ab"
path = "modules/benchmark/coremark"
groups = ["benchmark"]

[manifest.projects.nix]
hash = "sha256-KBzkjRV24chI7iLLCIFNXVTEgFv9/+DvzWH0aeq6QAU="

[[manifest.projects]]
name = "canopennode"
url = "https://github.com/zephyrproject-rtos/canopennode"
revision = "dec12fa3f0d790cafa8414a4c2930ea71ab72ffd"
path = "modules/lib/canopennode"
groups = ["optional"]

[manifest.projects.nix]
hash = "sha256-BbmEjeMzKznRDx329PIkmPMCGI+du6wiOj+3X7Ap1HQ="

[[manifest.projects]]
name = "chre"
url = "https://github.com/zephyrproject-rtos/chre"
revision = "3b32c76efee705af146124fb4190f71be5a4e36e"
path = "modules/lib/chre"
groups = ["optional"]

[manifest.projects.nix]
hash = "sha256-7SdP9zSKZ+6s+nkIcIbjZSnacq2/t06DiR2gcaL07T4="

[[manifest.projects]]
name = "lz4"
url = "https://github.com/zephyrproject-rtos/lz4"
revision = "11b8a1e22fa651b524494e55d22b69d3d9cebcfd"
path = "modules/lib/lz4"
groups = ["optional"]

[manifest.projects.nix]
hash = "sha256-6P6JUb7B/BfzhQLWaH7v4TNm5Yyz6OvGZmbZ8WM/65Q="

[[manifest.projects]]
name = "nanopb"
url = "https://github.com/zephyrproject-rtos/nanopb"
revision = "7307ce399b81ddcb3c3a5dc862c52d4754328d38"
path = "modules/lib/nanopb"
groups = ["optional"]

[manifest.projects.nix]
hash = "sha256-v06q2v1ifISPvO+0Elqa4N1q4/oxnG7C6lTj72Y2uZY="

[[manifest.projects]]
name = "tf-m-tests"
url = "https://github.com/zephyrproject-rtos/tf-m-tests"
revision = "c712761dd5391bf3f38033643d28a736cae89a19"
path = "modules/tee/tf-m/tf-m-tests"
groups = ["optional"]

[manifest.projects.nix]
hash = "sha256-KbkVSwyw/g8MzTrwHjraRg5yQ3AaTZYW67H0AJPUeGU="

[[manifest.projects]]
name = "zscilib"
url = "https://github.com/zephyrproject-rtos/zscilib"
revision = "ee3c0c405087e331aad16d167b6e4ec1c3452ba9"
path = "modules/lib/zscilib"
groups = ["optional"]

[manifest.projects.nix]
hash = "sha256-poUujJvsmTldIufvm7oW5vqUq5wlKljN833oTG484dU="

[[manifest.projects]]
name = "cmsis"
url = "https://github.com/zephyrproject-rtos/cmsis"
revision = "d1b8b20b6278615b00e136374540eb1c00dcabe7"
path = "modules/hal/cmsis"
groups = ["hal"]

[manifest.projects.nix]
hash = "sha256-41c6ugwL9D5aQHh6lLCTf2iJP0yAn8bVXOsVUsguuQg="

[[manifest.projects]]
name = "cmsis-dsp"
url = "https://github.com/zephyrproject-rtos/cmsis-dsp"
revision = "d80a49b2bb186317dc1db4ac88da49c0ab77e6e7"
path = "modules/lib/cmsis-dsp"

[manifest.projects.nix]
hash = "sha256-79wBXyHHqJXEGNNneBRfnr7DpmrC3jZjzEhC/kUbHgg="

[[manifest.projects]]
name = "cmsis-nn"
url = "https://github.com/zephyrproject-rtos/cmsis-nn"
revision = "e9328d612ea3ea7d0d210d3ac16ea8667c01abdd"
path = "modules/lib/cmsis-nn"

[manifest.projects.nix]
hash = "sha256-bD/58SYlCnBjBT6quUi3QH0dK49GgA8OqoLOKArQEik="

[[manifest.projects]]
name = "cmsis_6"
url = "https://github.com/zephyrproject-rtos/CMSIS_6"
revision = "6dd50439a9b83398ff2ae1376eef0a2a0b95913b"
path = "modules/hal/cmsis_6"
groups = ["hal"]

[manifest.projects.nix]
hash = "sha256-NaQ/2ko3xDqd5sPFAV/QB5WbHKscx1x0UB4WsYB5ppU="

[[manifest.projects]]
name = "edtt"
url = "https://github.com/zephyrproject-rtos/edtt"
revision = "b9ca3c7030518f07b7937dacf970d37a47865a76"
path = "tools/edtt"
groups = ["tools"]

[manifest.projects.nix]
hash = "sha256-wY2DmLk4TO2Q6pvKb3iBlRm9ShUd9ePxtPr9eJkSS5g="

[[manifest.projects]]
name = "fatfs"
url = "https://github.com/zephyrproject-rtos/fatfs"
revision = "16245c7c41d2b79e74984f49b5202551786b8a9b"
path = "modules/fs/fatfs"
groups = ["fs"]

[manifest.projects.nix]
hash = "sha256-pHr2E+ty2fEMrGpCBa/yVQpNEgBFV3brNmGXOZBPc5g="

[[manifest.projects]]
name = "hal_nordic"
url = "https://github.com/zephyrproject-rtos/hal_nordic"
revision = "2f5d4e5868ab573eac932fa4bc142565073c3c04"
path = "modules/hal/nordic"
groups = ["hal"]

[manifest.projects.nix]
hash = "sha256-Bi4z1ptvU3+SWlwSEH67yxokg5rPASEY1xs3tlPt74I="

[[manifest.projects]]
name = "hal_st"
url = "https://github.com/zephyrproject-rtos/hal_st"
revision = "9f81b4427e955885398805b7bca0da3a8cd9109c"
path = "modules/hal/st"
groups = ["hal"]

[manifest.projects.nix]
hash = "sha256-kpV0PCBd96ZbmKoLZtjrd0JovJK3++w56JdY0u7FP0Q="

[[manifest.projects]]
name = "hal_tdk"
url = "https://github.com/zephyrproject-rtos/hal_tdk"
revision = "6727477af1e46fa43878102489b9672a9d24e39f"
path = "modules/hal/tdk"
groups = ["hal"]

[manifest.projects.nix]
hash = "sha256-VJ+M9WD9FPfGmKfxI+uBIaLfPcADMtXaS5paQ67UjY0="

[[manifest.projects]]
name = "hal_wurthelektronik"
url = "https://github.com/zephyrproject-rtos/hal_wurthelektronik"
revision = "e3e2797b224fc48fdef1bc3e5a12a7c73108bba2"
path = "modules/hal/wurthelektronik"
groups = ["hal"]

[manifest.projects.nix]
hash = "sha256-Xf/xazKK3ttGV7hdvUQanust2AUGjDyt62h1yl1Sc7A="

[[manifest.projects]]
name = "liblc3"
url = "https://github.com/zephyrproject-rtos/liblc3"
revision = "48bbd3eacd36e99a57317a0a4867002e0b09e183"
path = "modules/lib/liblc3"

[manifest.projects.nix]
hash = "sha256-OWuj68+YztIh/dPvwqjW7ch7Ph3aiEIDvO9rMkVIrQ8="

[[manifest.projects]]
name = "libmetal"
url = "https://github.com/zephyrproject-rtos/libmetal"
revision = "14f519529a1e4a46aaea6826f5a41d99a3347276"
path = "modules/hal/libmetal"
groups = ["hal"]

[manifest.projects.nix]
hash = "sha256-sI7YxMjstLhm44K3GH0yk3eZX+ase2uCXJ5omo7Qn4Y="

[[manifest.projects]]
name = "littlefs"
url = "https://github.com/zephyrproject-rtos/littlefs"
revision = "8f5ca347843363882619d8f96c00d8dbd88a8e79"
path = "modules/fs/littlefs"
groups = ["fs"]

[manifest.projects.nix]
hash = "sha256-MuXfpmEE3z0ZOtfjp93aAh/7xZhShmHzwHC5nyN2QQg="

[[manifest.projects]]
name = "loramac-node"
url = "https://github.com/zephyrproject-rtos/loramac-node"
revision = "fb00b383072518c918e2258b0916c996f2d4eebe"
path = "modules/lib/loramac-node"

[manifest.projects.nix]
hash = "sha256-t6CRkm5TheFvUuc+Qj3JaveWYOaHRH6Pquvlb5YlsOg="

[[manifest.projects]]
name = "lvgl"
url = "https://github.com/zephyrproject-rtos/lvgl"
revision = "1ed1ddd881c3784049a92bb9fe37c38c6c74d998"
path = "modules/lib/gui/lvgl"

[manifest.projects.nix]
hash = "sha256-StW4k/m6YSPlJDNvf/pZOcbecq5i7Upu3StRJFy6/vo="

[[manifest.projects]]
name = "mipi-sys-t"
url = "https://github.com/zephyrproject-rtos/mipi-sys-t"
revision = "33e5c23cbedda5ba12dbe50c4baefb362a791001"
path = "modules/debug/mipi-sys-t"
groups = ["debug"]

[manifest.projects.nix]
hash = "sha256-rDsj8ZnJIfNaAhrjnx69U0nYVY9T5x5kmMsmFgn3wPA="

[[manifest.projects]]
name = "net-tools"
url = "https://github.com/zephyrproject-rtos/net-tools"
revision = "986bfeb040df3d9029366de8aea4ce1f84e93780"
path = "tools/net-tools"
groups = ["tools"]

[manifest.projects.nix]
hash = "sha256-XgL/LuMV4OVlSX8afa4K1r4En2vruzkvQXBH5zSH7dc="

[[manifest.projects]]
name = "nrf_hw_models"
url = "https://github.com/zephyrproject-rtos/nrf_hw_models"
revision = "968d55ff22579080466bf2f482596dd6e35361c6"
path = "modules/bsim_hw_models/nrf_hw_models"

[manifest.projects.nix]
hash = "sha256-MbsaAni4LLigGSgMsgLLqKGimU/4tQLxqK+d2dwULmE="

[[manifest.projects]]
name = "nrf_wifi"
url = "https://github.com/zephyrproject-rtos/nrf_wifi"
revision = "787eea1a3c8dd13c86214e204a919e6f9bcebf91"
path = "modules/lib/nrf_wifi"

[manifest.projects.nix]
hash = "sha256-6IBslJ0iYZfhYWcbGt1YLB42QnSZLWV6VuaG8VM/3/c="

[[manifest.projects]]
name = "open-amp"
url = "https://github.com/zephyrproject-rtos/open-amp"
revision = "f7f4d083c7909a39d86e217376c69b416ec4faf3"
path = "modules/lib/open-amp"

[manifest.projects.nix]
hash = "sha256-6BwbtMZM49C+SgB98A3FZS0Aw7SlFWu04GGaSdZqP0Q="

[[manifest.projects]]
name = "percepio"
url = "https://github.com/zephyrproject-rtos/percepio"
revision = "49e6dc202aa38c2a3edbafcc2dab85dec6aee973"
path = "modules/debug/percepio"
groups = ["debug"]

[manifest.projects.nix]
hash = "sha256-mDISi9mNw93HBesrRo0N01V5Ipl5awifYr+mNT2nJGM="

[[manifest.projects]]
name = "picolibc"
url = "https://github.com/zephyrproject-rtos/picolibc"
revision = "560946f26db075c296beea5b39d99e6de43c9010"
path = "modules/lib/picolibc"

[manifest.projects.nix]
hash = "sha256-22aCOAjDfEFtlUX3VCpsa/7VGYjObpYn7EkcyYnj/fg="

[[manifest.projects]]
name = "segger"
url = "https://github.com/zephyrproject-rtos/segger"
revision = "cf56b1d9c80f81a26e2ac5727c9cf177116a4692"
path = "modules/debug/segger"
groups = ["debug"]

[manifest.projects.nix]
hash = "sha256-RiQm92YGm+pZPLDcZxI9brNfIerumduLFNi6JKGj99E="

[[manifest.projects]]
name = "tinycrypt"
url = "https://github.com/zephyrproject-rtos/tinycrypt"
revision = "1012a3ebee18c15ede5efc8332ee2fc37817670f"
path = "modules/crypto/tinycrypt"
groups = ["crypto"]

[manifest.projects.nix]
hash = "sha256-JQmkN+ircGU5Ald1+Q4lysuxhZLg2mJpNQ92+agMoCQ="

[[manifest.projects]]
name = "uoscore-uedhoc"
url = "https://github.com/zephyrproject-rtos/uoscore-uedhoc"
revision = "54abc109c9c0adfd53c70077744c14e454f04f4a"
path = "modules/lib/uoscore-uedhoc"

[manifest.projects.nix]
hash = "sha256-HY0Ol0pALHO0HrnJjSXul3iysronUSTUi5C+F568HgI="

[[manifest.projects]]
name = "zcbor"
url = "https://github.com/zephyrproject-rtos/zcbor"
revision = "9b07780aca6fb21f82a241ba386ad9b379809337"
path = "modules/lib/zcbor"

[manifest.projects.nix]
hash = "sha256-PIxfJfj0WztvsBZPTybkyQ+XImU8b83UtYQwt02CVuc="

[manifest.self]
path = "wt-phase2"
