[manifest]
group-filter = ["-babblesim", "-bsec", "-doc-internal", "-dragoon", "-find-my", "-libmodem", "-nrf-802154"]

[[manifest.projects]]
name = "sdk-nrf"
url = "https://github.com/nrfconnect/sdk-nrf"
revision = "4c3fc0d44534f387a2d623eb1c85cbd2ffc8bcb6"
path = "nrf"
west-commands = "scripts/west-commands.yml"

[manifest.projects.nix]
hash = "sha256-etP8zFeEvsawAPSnHs1HWMQeFcQNF/IxPAm0PtLuC0s="

[[manifest.projects]]
name = "zephyr"
url = "https://github.com/nrfconnect/sdk-zephyr"
revision = "9673eec759087fd0f5bffb8d31f2be6b2aa1635f"
west-commands = "scripts/west-commands.yml"

[manifest.projects.nix]
hash = "sha256-fRrgzo+hX9zNucfx8j+Es7m9Xh5zEJsIMvvluCeZn20="

[[manifest.projects]]
name = "hostap"
url = "https://github.com/nrfconnect/sdk-hostap"
revision = "5c3a37f96cc8c474afa6b05e5d50f1c739788755"
path = "modules/lib/hostap"

[manifest.projects.nix]
hash = "sha256-3Xjb78vlSDCq2EVnTx+Wj1YqEM7OWEmOOO00DeO4XM0="

[[manifest.projects]]
name = "wfa-qt-control-app"
url = "https://github.com/nrfconnect/sdk-wi-fiquicktrack-controlappc"
revision = "d4bc010be69aa89290c5af6767702ff46c1829e5"
path = "modules/lib/wfa-qt-control-app"

[manifest.projects.userdata.ncs]
upstream-url = "https://github.com/Wi-FiQuickTrack/Wi-FiQuickTrack-ControlAppC"
upstream-sha = "1225729e8d84075f03bf9fc51eee85d84dfb0091"
compare-by-default = true

[manifest.projects.nix]
hash = "sha256-hDBebap/ENTqyC8FHtsUhDlLOTLiknKvaXfUexGJO0s="

[[manifest.projects]]
name = "mcuboot"
url = "https://github.com/nrfconnect/sdk-mcuboot"
revision = "d537e5b5d244317cc62f22fe86add1c637c21c12"
path = "bootloader/mcuboot"

[manifest.projects.nix]
hash = "sha256-8SVWqHzGZ1jFqV0LiwRmei8rBTfC5yt+F7zsxO0nvzs="

[[manifest.projects]]
name = "qcbor"
url = "https://github.com/laurencelundblade/QCBOR"
revision = "751d36583a9ce1a640900c57e13c9b6b8f3a2ba2"
path = "modules/tee/tf-m/qcbor"

[manifest.projects.nix]
hash = "sha256-heOCeSDrHCJA2T/iRnSXoRIl6WeS8KRDtEh9zK1Hkm8="

[[manifest.projects]]
name = "mbedtls"
url = "https://github.com/nrfconnect/sdk-mbedtls"
revision = "d77330677bef8221fff58c88fd0cd9ab4fd33cd8"
path = "modules/crypto/mbedtls"

[manifest.projects.nix]
hash = "sha256-wr3Rd7MfIvtk2p1Sd4O2pKmb57xPI6tgkwIvPxxegJo="

[[manifest.projects]]
name = "oberon-psa-crypto"
url = "https://github.com/nrfconnect/sdk-oberon-psa-crypto"
revision = "ee0cdb000b9ce3c699193a15312058c62e5afa57"
path = "modules/crypto/oberon-psa-crypto"

[manifest.projects.nix]
hash = "sha256-k4ZQI8s5KgfkZPgNDyuLjgEv1NqpPBQ5hXPOudhmq2Y="

[[manifest.projects]]
name = "nrfxlib"
url = "https://github.com/nrfconnect/sdk-nrfxlib"
revision = "015aa9b46f093e4f729763be03a4be9e89043bcc"

[manifest.projects.nix]
hash = "sha256-RZMLew7IgMM0VUMtDBWLd/qQGuNfIOlsetewRk9VmTw="

[[manifest.projects]]
name = "trusted-firmware-m"
url = "https://github.com/nrfconnect/sdk-trusted-firmware-m"
revision = "f36cea2c7dd9317fc0dbafc380a50666c822d02d"
path = "modules/tee/tf-m/trusted-firmware-m"

[manifest.projects.nix]
hash = "sha256-AtLgRNKfMXv5vUMl7EktP9Rvsd0nOMG8BNKTbfLdrx4="

[[manifest.projects]]
name = "psa-arch-tests"
url = "https://github.com/nrfconnect/sdk-psa-arch-tests"
revision = "ecd6864211894fca9d3cc4d87908f7b974c2a7d4"
path = "modules/tee/tf-m/psa-arch-tests"

[manifest.projects.nix]
hash = "sha256-xaaF68LpTyJljXTolJtDdhz5ZI8m8zP86UTi2QSar5U="

[[manifest.projects]]
name = "matter"
url = "https://github.com/nrfconnect/sdk-connectedhomeip"
revision = "6f3a83e7cf985265e89fed3fe567143efddbf670"
path = "modules/lib/matter"
west-commands = "scripts/west/west-commands.yml"

[[manifest.projects.submodules]]
path = "third_party/nlio/repo"
name = "nlio"

[[manifest.projects.submodules]]
path = "third_party/nlassert/repo"
name = "nlassert"

[[manifest.projects.submodules]]
path = "third_party/pigweed/repo"
name = "pigweed"

[[manifest.projects.submodules]]
path = "third_party/jsoncpp/repo"
name = "jsoncpp"

[manifest.projects.userdata.ncs]
upstream-url = "https://github.com/project-chip/connectedhomeip"
upstream-sha = "181b0cb14ff007ec912f2ba6627e05dfb066c008"
compare-by-default = false

[manifest.projects.nix]
hash = "sha256-Bxqe9KOQU9kk8+MkcXNivC7c+70Et7s7LT75zbPF7Tk="

[[manifest.projects]]
name = "cjson"
url = "https://github.com/nrfconnect/sdk-cjson"
revision = "c6af068b7f05207b28d68880740e4b9ec1e4b50a"
path = "modules/lib/cjson"

[manifest.projects.userdata.ncs]
upstream-url = "https://github.com/DaveGamble/cJSON"
upstream-sha = "d2735278ed1c2e4556f53a7a782063b31331dbf7"
compare-by-default = false

[manifest.projects.nix]
hash = "sha256-2WtrP+Dam6iFE5jRPskMxss82KfG7Sf+nc7Y+IuggDc="

[[manifest.projects]]
name = "azure-sdk-for-c"
url = "https://github.com/nrfconnect/azure-sdk-for-c"
revision = "308c171cb4b5eed266649012a68406487ec81fb2"
path = "modules/lib/azure-sdk-for-c"

[manifest.projects.userdata.ncs]
upstream-url = "https://github.com/Azure/azure-sdk-for-c"
upstream-sha = "adc56bc6138a28b5490bce339a31a2581a072092"
compare-by-default = false

[manifest.projects.nix]
hash = "sha256-sBnvtWz9QH4lrb3q+xI/MqFO8LWrhVN8+VsHX0RdZSM="

[[manifest.projects]]
name = "cirrus"
url = "https://github.com/nrfconnect/sdk-mcu-drivers"
revision = "1c837bcc27de9ccc06b020b9500e1547e559a1df"
path = "modules/hal/cirrus-logic"

[manifest.projects.userdata.ncs]
upstream-url = "https://github.com/CirrusLogic/mcu-drivers"
upstream-sha = "1be6ca7253133a21a1e9fe0fbb4656e17d63a936"
compare-by-default = false

[manifest.projects.nix]
hash = "sha256-L8jHNR22n27dkP7XqJ/pQ0U1QcaC2gt02W+P9P3L/DA="

[[manifest.projects]]
name = "openthread"
url = "https://github.com/nrfconnect/sdk-openthread"
revision = "0e26667136c2c49d42c96b8104ec2e90e8d55e4d"
path = "modules/lib/openthread"

[manifest.projects.userdata.ncs]
upstream-url = "https://github.com/openthread/openthread"
upstream-sha = "c6eaeda5a1c1c5dbb24dce7e027340cb8893a77b"
compare-by-default = false

[manifest.projects.nix]
hash = "sha256-MzsrLeklp1simIwJh2Y0b7dKNlMkal6SlNHXFvpqyfE="

[[manifest.projects]]
name = "cmock"
url = "https://github.com/ThrowTheSwitch/cmock"
revision = "f65066f15d8248e6dcb778efb8739904a4512087"
path = "test/cmock"
submodules = true

[manifest.projects.nix]
hash = "sha256-0JbIT3db/NlBtkf6xCIVtYsWiC0j9RCYAKbBhrroyoA="

[[manifest.projects]]
name = "memfault-firmware-sdk"
url = "https://github.com/memfault/memfault-firmware-sdk"
revision = "e29551ff881c966805522c9fd9b7b14b8e2f2492"
path = "modules/lib/memfault-firmware-sdk"

[manifest.projects.nix]
hash = "sha256-HC3G38Uu0b6oibHgltTlUv9u0HP7++PGQnnkcPQme4A="

[[manifest.projects]]
name = "bsim"
url = "https://github.com/BabbleSim/bsim_west"
revision = "a88d3353451387ca490a6a7f7c478a90c4ee05b7"
path = "tools/bsim"

[manifest.projects.nix]
hash = "sha256-fukVH/2GJtWw3YWrTWSzMEW80jqdhWq8xhlt/0xhxrI="

[[manifest.projects]]
name = "coremark"
url = "https://github.com/eembc/coremark"
revision = "d5fad6bd094899101a4e5fd53af7298160ced6ab"
path = "modules/benchmark/coremark"
groups = ["benchmark"]

[manifest.projects.nix]
hash = "sha256-KBzkjRV24chI7iLLCIFNXVTEgFv9/+DvzWH0aeq6QAU="

[[manifest.projects]]
name = "canopennode"
url = "https://github.com/zephyrproject-rtos/canopennode"
revision = "dec12fa3f0d790cafa8414a4c2930ea71ab72ffd"
path = "modules/lib/canopennode"
groups = ["optional"]

[manifest.projects.nix]
hash = "sha256-BbmEjeMzKznRDx329PIkmPMCGI+du6wiOj+3X7Ap1HQ="

[[manifest.projects]]
name = "chre"
url = "https://github.com/zephyrproject-rtos/chre"
revision = "3b32c76efee705af146124fb4190f71be5a4e36e"
path = "modules/lib/chre"
groups = ["optional"]

[manifest.projects.nix]
hash = "sha256-7SdP9zSKZ+6s+nkIcIbjZSnacq2/t06DiR2gcaL07T4="

[[manifest.projects]]
name = "lz4"
url = "https://github.com/zephyrproject-rtos/lz4"
revision = "11b8a1e22fa651b524494e55d22b69d3d9cebcfd"
path = "modules/lib/lz4"
groups = ["optional"]

[manifest.projects.nix]
hash = "sha256-6P6JUb7B/BfzhQLWaH7v4TNm5Yyz6OvGZmbZ8WM/65Q="

[[manifest.projects]]
name = "tf-m-tests"
url = "https://github.com/zephyrproject-rtos/tf-m-tests"
revision = "a90702bcb8fadb6f70daf0ffbb13888dfe63fc99"
path = "modules/tee/tf-m/tf-m-tests"
groups = ["optional"]

[manifest.projects.nix]
hash = "sha256-o+EIVgBrX/6Rhk12eDj3qfzp/QfrR9MEHu3bUuFp1cE="

[[manifest.projects]]
name = "zscilib"
url = "https://github.com/zephyrproject-rtos/zscilib"
revision = "ee3c0c405087e331aad16d167b6e4ec1c3452ba9"
path = "modules/lib/zscilib"
groups = ["optional"]

[manifest.projects.nix]
hash = "sha256-poUujJvsmTldIufvm7oW5vqUq5wlKljN833oTG484dU="

[[manifest.projects]]
name = "cmsis"
url = "https://github.com/zephyrproject-rtos/cmsis"
revision = "512cc7e895e8491696b61f7ba8066b4a182569b8"
path = "modules/hal/cmsis"
groups = ["hal"]

[manifest.projects.nix]
hash = "sha256-IR4Za8TuYY7nkqK57xUJ2uWnCp7wB9B4/ZjhalLhCUU="

[[manifest.projects]]
name = "cmsis-dsp"
url = "https://github.com/zephyrproject-rtos/cmsis-dsp"
revision = "97512610ec92058f0119450b9e743eeb7e95b5c8"
path = "modules/lib/cmsis-dsp"

[manifest.projects.nix]
hash = "sha256-Lxmu9fPuLtaPiDRhZWLYoihKC6TEBb5j3iTouT6Vv3E="

[[manifest.projects]]
name = "cmsis-nn"
url = "https://github.com/zephyrproject-rtos/cmsis-nn"
revision = "e9328d612ea3ea7d0d210d3ac16ea8667c01abdd"
path = "modules/lib/cmsis-nn"

[manifest.projects.nix]
hash = "sha256-bD/58SYlCnBjBT6quUi3QH0dK49GgA8OqoLOKArQEik="

[[manifest.projects]]
name = "cmsis_6"
url = "https://github.com/zephyrproject-rtos/CMSIS_6"
revision = "30a859f44ef8ab4dc8f84b03ed586fd16ccf9d74"
path = "modules/hal/cmsis_6"
groups = ["hal"]

[manifest.projects.nix]
hash = "sha256-nTehISN0pu9gnOZMpGaBQ3DFmNxAqAZPGpvbKfEM35o="

[[manifest.projects]]
name = "edtt"
url = "https://github.com/zephyrproject-rtos/edtt"
revision = "b9ca3c7030518f07b7937dacf970d37a47865a76"
path = "tools/edtt"
groups = ["tools"]

[manifest.projects.nix]
hash = "sha256-wY2DmLk4TO2Q6pvKb3iBlRm9ShUd9ePxtPr9eJkSS5g="

[[manifest.projects]]
name = "fatfs"
url = "https://github.com/zephyrproject-rtos/fatfs"
revision = "18ad3932f7f18b59abf99cb2f8a6cd5d6746cfe0"
path = "modules/fs/fatfs"
groups = ["fs"]

[manifest.projects.nix]
hash = "sha256-cqbNNC1vfrkccDNhvPT3TIYwaPZvcqYI9m0a1zO1cUo="

[[manifest.projects]]
name = "hal_nordic"
url = "https://github.com/zephyrproject-rtos/hal_nordic"
revision = "0dbbf4794156ca09dc2d4bad8c42dcdb54acd662"
path = "modules/hal/nordic"
groups = ["hal"]

[manifest.projects.nix]
hash = "sha256-OzkGLeQWAXHlgaiR7Y6Su2HMdMNUR2efHg/gwi1I2Hg="

[[manifest.projects]]
name = "hal_st"
url = "https://github.com/zephyrproject-rtos/hal_st"
revision = "9f81b4427e955885398805b7bca0da3a8cd9109c"
path = "modules/hal/st"
groups = ["hal"]

[manifest.projects.nix]
hash = "sha256-kpV0PCBd96ZbmKoLZtjrd0JovJK3++w56JdY0u7FP0Q="

[[manifest.projects]]
name = "hal_tdk"
url = "https://github.com/zephyrproject-rtos/hal_tdk"
revision = "6727477af1e46fa43878102489b9672a9d24e39f"
path = "modules/hal/tdk"
groups = ["hal"]

[manifest.projects.nix]
hash = "sha256-VJ+M9WD9FPfGmKfxI+uBIaLfPcADMtXaS5paQ67UjY0="

[[manifest.projects]]
name = "hal_wurthelektronik"
url = "https://github.com/zephyrproject-rtos/hal_wurthelektronik"
revision = "e3e2797b224fc48fdef1bc3e5a12a7c73108bba2"
path = "modules/hal/wurthelektronik"
groups = ["hal"]

[manifest.projects.nix]
hash = "sha256-Xf/xazKK3ttGV7hdvUQanust2AUGjDyt62h1yl1Sc7A="

[[manifest.projects]]
name = "liblc3"
url = "https://github.com/zephyrproject-rtos/liblc3"
revision = "48bbd3eacd36e99a57317a0a4867002e0b09e183"
path = "modules/lib/liblc3"

[manifest.projects.nix]
hash = "sha256-OWuj68+YztIh/dPvwqjW7ch7Ph3aiEIDvO9rMkVIrQ8="

[[manifest.projects]]
name = "libmetal"
url = "https://github.com/zephyrproject-rtos/libmetal"
revision = "91d38634d1882f0a2151966f8c5c230ce1c0de7b"
path = "modules/hal/libmetal"
groups = ["hal"]

[manifest.projects.nix]
hash = "sha256-xaX5Dp9Vj8ovvHYf6c439WXOflji6J9GtCNGbGeh6Tk="

[[manifest.projects]]
name = "littlefs"
url = "https://github.com/zephyrproject-rtos/littlefs"
revision = "8f5ca347843363882619d8f96c00d8dbd88a8e79"
path = "modules/fs/littlefs"
groups = ["fs"]

[manifest.projects.nix]
hash = "sha256-MuXfpmEE3z0ZOtfjp93aAh/7xZhShmHzwHC5nyN2QQg="

[[manifest.projects]]
name = "loramac-node"
url = "https://github.com/zephyrproject-rtos/loramac-node"
revision = "fb00b383072518c918e2258b0916c996f2d4eebe"
path = "modules/lib/loramac-node"

[manifest.projects.nix]
hash = "sha256-t6CRkm5TheFvUuc+Qj3JaveWYOaHRH6Pquvlb5YlsOg="

[[manifest.projects]]
name = "lvgl"
url = "https://github.com/zephyrproject-rtos/lvgl"
revision = "b03edc8e6282a963cd312cd0b409eb5ce263ea75"
path = "modules/lib/gui/lvgl"

[manifest.projects.nix]
hash = "sha256-akmYjcyRikKxG9W37u+3aal+BbeBltbprmCxkzGAPp4="

[[manifest.projects]]
name = "mipi-sys-t"
url = "https://github.com/zephyrproject-rtos/mipi-sys-t"
revision = "33e5c23cbedda5ba12dbe50c4baefb362a791001"
path = "modules/debug/mipi-sys-t"
groups = ["debug"]

[manifest.projects.nix]
hash = "sha256-rDsj8ZnJIfNaAhrjnx69U0nYVY9T5x5kmMsmFgn3wPA="

[[manifest.projects]]
name = "nanopb"
url = "https://github.com/zephyrproject-rtos/nanopb"
revision = "7307ce399b81ddcb3c3a5dc862c52d4754328d38"
path = "modules/lib/nanopb"

[manifest.projects.nix]
hash = "sha256-v06q2v1ifISPvO+0Elqa4N1q4/oxnG7C6lTj72Y2uZY="

[[manifest.projects]]
name = "net-tools"
url = "https://github.com/zephyrproject-rtos/net-tools"
revision = "2750d71e28e48865a6fd8a10413f978bb216c59e"
path = "tools/net-tools"
groups = ["tools"]

[manifest.projects.nix]
hash = "sha256-BMlC2p6XDsol+m/iIKJwtHTfUNvauRNpECzPG6Rt2QY="

[[manifest.projects]]
name = "nrf_hw_models"
url = "https://github.com/zephyrproject-rtos/nrf_hw_models"
revision = "5eec7aca321735f5fc8e3e7c79e162f0e9810b16"
path = "modules/bsim_hw_models/nrf_hw_models"

[manifest.projects.nix]
hash = "sha256-7DuJnhpbmIOqHsKnR/5SP6Wi6it+ac4vc0kG541e434="

[[manifest.projects]]
name = "nrf_wifi"
url = "https://github.com/zephyrproject-rtos/nrf_wifi"
revision = "97c6751657187ab811e73c36cc4c47acb1783fff"
path = "modules/lib/nrf_wifi"

[manifest.projects.nix]
hash = "sha256-cSyVqHUZgthoSfwS/hvsbRNI5jK0uT0rTHG15B0yteA="

[[manifest.projects]]
name = "open-amp"
url = "https://github.com/zephyrproject-rtos/open-amp"
revision = "c30a6d8b92fcebdb797fc1a7698e8729e250f637"
path = "modules/lib/open-amp"

[manifest.projects.nix]
hash = "sha256-WRYNd848wZNb8EfM+XbLb0vqwpK6hncJK7Q29HbU6Co="

[[manifest.projects]]
name = "percepio"
url = "https://github.com/zephyrproject-rtos/percepio"
revision = "49e6dc202aa38c2a3edbafcc2dab85dec6aee973"
path = "modules/debug/percepio"
groups = ["debug"]

[manifest.projects.nix]
hash = "sha256-mDISi9mNw93HBesrRo0N01V5Ipl5awifYr+mNT2nJGM="

[[manifest.projects]]
name = "picolibc"
url = "https://github.com/zephyrproject-rtos/picolibc"
revision = "560946f26db075c296beea5b39d99e6de43c9010"
path = "modules/lib/picolibc"

[manifest.projects.nix]
hash = "sha256-22aCOAjDfEFtlUX3VCpsa/7VGYjObpYn7EkcyYnj/fg="

[[manifest.projects]]
name = "segger"
url = "https://github.com/zephyrproject-rtos/segger"
revision = "cf56b1d9c80f81a26e2ac5727c9cf177116a4692"
path = "modules/debug/segger"
groups = ["debug"]

[manifest.projects.nix]
hash = "sha256-RiQm92YGm+pZPLDcZxI9brNfIerumduLFNi6JKGj99E="

[[manifest.projects]]
name = "uoscore-uedhoc"
url = "https://github.com/zephyrproject-rtos/uoscore-uedhoc"
revision = "54abc109c9c0adfd53c70077744c14e454f04f4a"
path = "modules/lib/uoscore-uedhoc"

[manifest.projects.nix]
hash = "sha256-HY0Ol0pALHO0HrnJjSXul3iysronUSTUi5C+F568HgI="

[[manifest.projects]]
name = "zcbor"
url = "https://github.com/zephyrproject-rtos/zcbor"
revision = "9b07780aca6fb21f82a241ba386ad9b379809337"
path = "modules/lib/zcbor"

[manifest.projects.nix]
hash = "sha256-PIxfJfj0WztvsBZPTybkyQ+XImU8b83UtYQwt02CVuc="

[manifest.self]
path = "wt-phase3"
